version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: UTC
  open-pull-requests-limit: 15
  commit-message:
    prefix: build
    include: scope
